### ISSUE TITLE
Completely blue screenshots

### ISSUE THREAD

**Issue by Axodique** [LudoCrypt/Vistas#30] opened 2022-08-30 16:49 UTC
![panorama_0](https://user-images.githubusercontent.com/49350272/187493813-6daca856-4dd0-4c70-a34a-0d39558efe8e.png)

All my panorama screenshots look completely blue like this.

[modlist just in case](https://pastebin.com/M8uY9cEN)

**Comment by gniftygnome** [comment] 2022-08-30 16:56
This is a duplicate of #22 and seems to be caused by some conflict with iris or sodium ... most reports only include the blue screen-shot part so I suspect the blank screen was resolved in a later version of Minecraft, iris, or sodium.

**Closed as not planned** 2022-08-30 16:57 UTC

**Comment by Axodique** [comment] 2022-08-31 20:45
> This is a duplicate of #22 and seems to be caused by some conflict with iris or sodium ... most reports only include the blue screen-shot part so I suspect the blank screen was resolved in a later version of Minecraft, iris, or sodium.

I'd like to say that it is an Iris problem, I uninstalled Iris and the mod worked as planned.
